image: gitpod/workspace-full

tasks:
  - init: |
      pnpm install
      alias nx="pnpm exec nx"
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - esbenp.prettier-vscode
